// <auto-generated />
using System;
using BETSoft.Services.Identity.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BETSoft.Services.Identity.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210502153311_ConfigureDefaultIdentityTables")]
    partial class ConfigureDefaultIdentityTables : ConfigureDefaultIdentityTablesBase
    {
    }
}
